### ISSUE TITLE
Could you reduce the dependency list?

### ISSUE THREAD

**Issue by brynpickering** [conda-forge/python-benedict-feedstock#35]
### Comment:

You have a lot of optional requirements defined in your main repo [README](https://github.com/fabiocaccamo/python-benedict#optional-requirements). These are then defined as strict requirements in the conda-forge package. The result is quite a lot of dependencies if you only want `python-benedict` for loading from / dumping to one or two filetypes.

Would it be possible to either have many of these dependencies moved to being optional (but constrained to your preferred version pinning using `requirements.run_constrained`), or to have a `python-benedict-core` conda forge package that is the bare minimum?

It's relatively easy when creating a conda package to just include the "optional" dependencies by name when installing `python-benedict`. In my use-case, I really only need YAML read-write, but end up with boto, xml, xlrd, etc. etc.

**Comment by efiop** [comment]
@brynpickering Do you have any other packages in mind with a similar problem? Just curious how it is usually solved with conda. From a quick look around, I see that pandas, for example, seems to just not include any optional deps at all, indeed letting the user to specify those separately on his own.

**Comment by brynpickering** [comment]
Yes, this is also the case for xarray: 
optional dependencies in pyproject.toml: https://github.com/pydata/xarray/blob/main/pyproject.toml
`run-constrained` in feedstock recipe: https://github.com/conda-forge/xarray-feedstock/blob/main/recipe/meta.yaml

So it does seem that libraries with I/O options leave them as optional dependencies.

For having a "core" module, [`boto3`](https://github.com/conda-forge/boto3-feedstock) relies on [`botocore`](https://github.com/conda-forge/botocore-feedstock). It's a bit more difficult to find good examples of this approach though.

**Comment by efiop** [comment]
@brynpickering Makes sense to me. Feel free to submit a PR if you are keen.
